name: Setup D1 Database

inputs:
  database-name:
    required: true
    type: string
  cloudflare-api-token:
    required: true
    type: string
  cloudflare-account-id:
    required: true
    type: string
     
jobs: 
  setup-database:
    runs-on: ubuntu-22.04
    outputs:
      database-id: ${{ steps.db-setup.outputs.database-id }}
    steps:
      - uses: actions/checkout@v6
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --ignore-scripts --frozen-lockfile
      
      - name: List D1 Databases
        id: list-db
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ inputs.cloudflare-api-token }}
          accountId: ${{ inputs.cloudflare-account-id }}
          command: d1 list --json
          workingDirectory: apps/backend
      - name: Check if DB exists and create if needed
        id: db-setup
        run: |
          DB_NAME="${{ inputs.database-name }}"
          EXISTING_DB=$(echo '${{ steps.list-db.outputs.command-output }}' | jq -r --arg name "$DB_NAME" '.[] | select(.name == $name) | .uuid')
          
          if [ -n "$EXISTING_DB" ]; then
            echo "Database already exists with ID: $EXISTING_DB"
            echo "database-id=$EXISTING_DB" >> $GITHUB_OUTPUT
          else
            echo "Creating new database..."
            cd apps/backend
            CREATE_OUTPUT=$(npx wrangler d1 create "$DB_NAME" --json)
            DB_ID=$(echo "$CREATE_OUTPUT" | jq -r '.uuid')
            echo "database-id=$DB_ID" >> $GITHUB_OUTPUT
            echo "Created database with ID: $DB_ID"
          fi
        env:
          CLOUDFLARE_API_TOKEN: ${{ inputs.cloudflare-api-token }}
          CLOUDFLARE_ACCOUNT_ID: ${{ inputs.cloudflare-account-id }}
