#!/usr/bin/env node
/** biome-ignore-all lint/suspicious/noConsole: CLI script */
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { z } from 'zod'

// === Types ===

interface LocalConfig {
  mode: 'local'
  username: string
  databaseId?: string
}

interface PrConfig {
  mode: 'pr'
  prNumber: number
  databaseId?: string
}

type GenerateConfig = LocalConfig | PrConfig

interface AppConfig {
  appName: string
  urlPattern: string
  localRequiresDatabase: boolean
  prRequiresDatabase: boolean
  supportsLocal: boolean
}

// === App Configurations ===

const APP_CONFIGS: Record<string, AppConfig> = {
  api: {
    appName: 'api',
    localRequiresDatabase: true,
    prRequiresDatabase: true,
    supportsLocal: true,
    urlPattern: 'api-pr-$PR.downtown65.com',
  },
  events: {
    appName: 'events',
    localRequiresDatabase: false,
    prRequiresDatabase: false,
    supportsLocal: false,
    urlPattern: 'events-pr-$PR.downtown65.com',
  },
}

// === Config Generation ===

const GENERATED_WARNING = `//
// ⚠️  AUTO-GENERATED FILE
//
// This file is automatically generated by @downtown65/wrangler-config
// DO NOT EDIT MANUALLY
//
// To modify configuration, update the appropriate template file instead:
//   - wrangler.local.template.jsonc (for local development)
//
`

function getTemplateFile(mode: 'local' | 'pr'): string {
  return mode === 'local' ? 'wrangler.template.local.jsonc' : 'wrangler.jsonc'
}

function getOutputFile(mode: 'local' | 'pr'): string {
  return mode === 'local' ? 'wrangler.local.jsonc' : 'wrangler.pr.jsonc'
}

function replaceVariables(template: string, config: GenerateConfig): string {
  let result = template

  if (config.mode === 'local') {
    result = result.replace(/\$USERNAME/g, config.username)
    if (config.databaseId) {
      result = result.replace(/\$DATABASE_ID/g, config.databaseId)
    }
  } else {
    result = result.replace(/\$PR_NUMBER/g, String(config.prNumber))
    if (config.databaseId) {
      result = result.replace(/\$PR_DATABASE_ID/g, config.databaseId)
    }
  }

  return result
}

function generateWranglerConfig(
  config: GenerateConfig,
  cwd: string,
): { outputPath: string; templateFile: string } {
  const templateFile = getTemplateFile(config.mode)
  const templatePath = join(cwd, templateFile)
  const template = readFileSync(templatePath, 'utf-8')

  const result = `${GENERATED_WARNING}${replaceVariables(template, config)}`

  const outputFile = getOutputFile(config.mode)
  const outputPath = join(cwd, outputFile)
  writeFileSync(outputPath, result)

  return { outputPath, templateFile }
}

// === CLI ===

function detectApp(cwd: string): AppConfig {
  if (cwd.includes('apps/api')) return APP_CONFIGS.api
  if (cwd.includes('apps/events')) return APP_CONFIGS.events
  return APP_CONFIGS.api
}

function parseArgs(
  args: string[],
  appConfig: AppConfig,
): GenerateConfig | null {
  const mode = args[0]

  if (mode === 'local') {
    if (!appConfig.supportsLocal) {
      return null
    }

    const schemaWithDb = z
      .tuple([z.literal('local'), z.string().min(1), z.string().uuid()])
      .transform(([, username, databaseId]) => ({
        databaseId,
        mode: 'local' as const,
        username,
      }))

    const schemaWithoutDb = z
      .tuple([z.literal('local'), z.string().min(1)])
      .transform(([, username]) => ({
        databaseId: undefined,
        mode: 'local' as const,
        username,
      }))

    const schema = appConfig.localRequiresDatabase
      ? schemaWithDb
      : z.union([schemaWithDb, schemaWithoutDb])

    const result = schema.safeParse(args)
    if (!result.success) return null

    return result.data
  }

  if (mode === 'pr') {
    const schemaWithDb = z
      .tuple([z.literal('pr'), z.coerce.number().int().positive(), z.uuid()])
      .transform(([, prNumber, databaseId]) => ({
        databaseId,
        mode: 'pr' as const,
        prNumber,
      }))

    const schemaWithoutDb = z
      .tuple([z.literal('pr'), z.coerce.number().int().positive()])
      .transform(([, prNumber]) => ({
        databaseId: undefined,
        mode: 'pr' as const,
        prNumber,
      }))

    const schema = appConfig.prRequiresDatabase
      ? schemaWithDb
      : z.union([schemaWithDb, schemaWithoutDb])

    const result = schema.safeParse(args)
    if (!result.success) return null

    return result.data
  }

  return null
}

function printUsage(appConfig: AppConfig) {
  console.error('Usage:')
  if (appConfig.supportsLocal) {
    if (appConfig.localRequiresDatabase) {
      console.error('  generate-wrangler-config local <USERNAME> <DATABASE_ID>')
    } else {
      console.error('  generate-wrangler-config local <USERNAME> [DATABASE_ID]')
    }
  }
  if (appConfig.prRequiresDatabase) {
    console.error('  generate-wrangler-config pr <PR_NUMBER> <DATABASE_ID>')
  } else {
    console.error('  generate-wrangler-config pr <PR_NUMBER>')
  }
}

function main() {
  const cwd = process.cwd()
  const appConfig = detectApp(cwd)
  const args = process.argv.slice(2)

  const config = parseArgs(args, appConfig)

  if (!config) {
    console.error('❌ Invalid arguments\n')
    printUsage(appConfig)
    process.exit(1)
  }

  try {
    const { outputPath, templateFile } = generateWranglerConfig(config, cwd)

    const outputFile = getOutputFile(config.mode)
    console.log(`✅ Generated ${outputFile}`)
    console.log(`   Template: ${templateFile}`)

    if (config.mode === 'local') {
      console.log(`   Username: ${config.username}`)
      if (config.databaseId) {
        console.log(`   Database ID: ${config.databaseId}`)
      }
    } else {
      console.log(`   PR Number: ${config.prNumber}`)
      if (config.databaseId) {
        console.log(`   Database ID: ${config.databaseId}`)
      }
      const url = appConfig.urlPattern.replace('$PR', String(config.prNumber))
      console.log(`   URL: https://${url}`)
    }

    console.log(`   Output: ${outputPath}`)
  } catch (error) {
    if (error instanceof Error) {
      console.error(`❌ Error: ${error.message}`)
    } else {
      console.error('❌ Unknown error:', error)
    }
    process.exit(1)
  }
}

main()
