name: Setup Project
description: Sets up the project by installing dependencies.

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v6
      with:
        node-version: 22
        cache: pnpm
    - name: Install dependencies
      shell: bash
      run: pnpm install --ignore-scripts --frozen-lockfile
