name: Close Pull Request

on:
    pull_request:
        types:
            - closed

env:
    PR_NUMBER: ${{ github.event.pull_request.number }}
    PR_DATABASE_ID: "00000000-0000-0000-0000-000000000000" # Dummy Database ID; value is not needed for deletion
    DATABASE_NAME: "pr-${{ github.event.pull_request.number }}-dt65-events"

jobs:
    merged:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-22.04
        steps:
            - run: |
                  echo The PR was merged
    remove-backend:
        runs-on: ubuntu-22.04
        environment: development
        steps:
            - uses: actions/checkout@v6
            - uses: ./.github/actions/setup-project
            - name: Generate wrangler config for PR
              working-directory: apps/backend
              run: |
                  envsubst < wrangler.jsonc > wrangler.jsonc.tmp
                  mv wrangler.jsonc.tmp wrangler.jsonc

                  echo "Wrangler config after replacements:"
                  cat wrangler.jsonc
            - name: Close Preview Environment
              uses: cloudflare/wrangler-action@v3
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
                  workingDirectory: apps/backend
                  environment: pull-request
                  preCommands: npx wrangler d1 delete ${{ env.DATABASE_NAME }} -y
                  command: npx wrangler delete
    remove-frontend:
        runs-on: ubuntu-22.04
        environment: development
        steps:
            - uses: actions/checkout@v6
            - uses: ./.github/actions/setup-project
            - name: Generate wrangler config for PR
              working-directory: apps/frontend
              run: |
                  envsubst < wrangler.jsonc > wrangler.jsonc.tmp
                  mv wrangler.jsonc.tmp wrangler.jsonc

                  echo "Wrangler config after replacements:"
                  cat wrangler.jsonc
            - name: Close Preview Environment
              uses: cloudflare/wrangler-action@v3
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
                  workingDirectory: apps/frontend
                  environment: pull-request
                  command: npx wrangler delete
