name: Pull Request CI/CD

on:
  pull_request:
    branches: ["staging"]
    paths:
      - "apps/**"
      - "packages/**"
      - "pnpm-lock.yaml"

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  quality-checks:
    uses: ./.github/workflows/quality-checks.yaml
    secrets: inherit

  deploy-api:
    needs: [quality-checks]
    uses: ./.github/workflows/_deploy-api.yaml
    with:
      environment: pull-request
      pr-number: ${{ github.event.pull_request.number }}
    secrets: inherit

  deploy-events:
    needs: [quality-checks, deploy-api]
    uses: ./.github/workflows/_deploy-events.yaml
    with:
      environment: pull-request
      pr-number: ${{ github.event.pull_request.number }}
    secrets: inherit

  deploy-www:
    needs: [quality-checks, deploy-api]
    uses: ./.github/workflows/_deploy-www.yaml
    with:
      environment: pull-request
    secrets: inherit
