name: Pull Request

on:
  pull_request:
    branches: ["staging"]

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  deploy-backend:
    uses: ./.github/workflows/deploy-pull-request-backend.yaml
    with:
      pr-number: ${{ github.event.pull_request.number }}
    secrets: inherit
  deploy-frontend:
    uses: ./.github/workflows/deploy-pull-request-frontend.yaml
    with:
      pr-number: ${{ github.event.pull_request.number }}
    secrets: inherit
  quality-checks:
    uses: ./.github/workflows/quality-checks.yaml
    with:
      cloudflare-environment: pull-request
    secrets: inherit
