name: Pull Request

on:
  pull_request:
    branches: ["staging"]

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  deploy-api:
    uses: ./.github/workflows/deploy-pull-request-api.yaml
    with:
      pr-number: ${{ github.event.pull_request.number }}
    secrets: inherit
  deploy-events:
    uses: ./.github/workflows/deploy-pull-request-events.yaml
    with:
      pr-number: ${{ github.event.pull_request.number }}
    secrets: inherit
  quality-checks:
    uses: ./.github/workflows/quality-checks.yaml
    with:
      cloudflare-environment: pull-request
    secrets: inherit
