name: Push to Staging or Production

on:
  push:
    branches:
      - staging
  workflow_call:
    inputs:
      ref:
        description: "Branch ref main"
        required: true
        type: string

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy-backend:
    uses: ./.github/workflows/deploy-backend.yaml
    with:
      wrangler-environment: ${{ github.ref_name == 'main' && 'production' || 'staging' }}
      # TODO: needed for migrations. Check if we can improve this later.
      database-name: ${{ github.ref_name == 'main' && 'production-dt65-events' || 'staging-dt65-events' }}
    secrets: inherit
  deploy-frontend:
    uses: ./.github/workflows/deploy-frontend.yaml
    needs: deploy-backend
    with:
      wrangler-environment: ${{ github.ref_name == 'main' && 'production' || 'staging' }}
    secrets: inherit
