name: Quality Checks

on:
  workflow_call:

jobs:
  checks:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-project
      - name: Generate Files for API
        working-directory: apps/api
        run: |
          # Generate types for Frontend (SMELL)
          pnpm generate:openapi
          npx wrangler types --strict-vars false -c wrangler.jsonc --env unit-test
          # needed for knip
          pnpm run migrations:flatten

      - name: Generate Events types
        working-directory: apps/events
        run: |
          pnpm run generate:react-router-types
          pnpm run generate:api-types:file
          npx wrangler types --config wrangler.jsonc --env unit-test

      - name: Lint
        run: pnpm run ci:lint

      - name: Typecheck
        run: pnpm run typecheck

      - name: Version Check
        run: pnpm run sherif

      - name: Dead code check
        run: pnpm run knip --reporter github-actions

      - name: Unit tests
        run: pnpm run test
